export const CREATE_EVENT = "CREATE_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const DELETE_ALL_EVENTS = "DELETE_ALL_EVENT";
// 操作ログ用の定数
export const ADD_OPERATION_LOG = "ADD＿OPERATION＿LOG";
export const DELETE_ALL_OPERATION_LOGS = "DELETE_ALL_OPERATION_LOGS";
